.MODEL SMALL
.STACK 64
.DATA
PREGREET DB 'HELLO, '
GREETLEN DB 8 
STARTINGCURSOR DB 80 
CTR DB 0 
TOTALLEN DB 0


PARA_LIST LABEL BYTE
MAX_LEN DB 20
ACT_LEN DB ?
KB_DATA DB 20 DUP(' ')     

.CODE
MAIN PROC NEAR
    MOV AX, @DATA
    MOV ES, AX
    MOV DS, AX
    
    CALL TAKESTRINGINPUT
    CALL SETSTARTINGCURSOR
    CALL SETVIDEOMODE
    CALL SETSCREENCOLOR  
    CALL DISPLAYSTRING
       
    MOV AX, 4C00H
    INT 21H
MAIN ENDP             

;PROCEDURES

SETVIDEOMODE PROC NEAR
    MOV AH, 00H
    MOV AL, 03H
    
    INT 10H
    
    RET
SETVIDEOMODE ENDP

TAKESTRINGINPUT PROC NEAR
    MOV AH, 0AH
    LEA DX, PARA_LIST
    
    INT 21H
    
    RET
TAKESTRINGINPUT ENDP 

SETSTARTINGCURSOR PROC NEAR 
    MOV AL, ACT_LEN 
    ADD AL, GREETLEN
    ;MOV AL, TOTALLEN
    
    SUB STARTINGCURSOR, AL
    MOV AH, 00
    MOV AL, STARTINGCURSOR
    MOV BL, 2  
    DIV BL
    
    MOV STARTINGCURSOR, AL
    
    
    RET
SETSTARTINGCURSOR ENDP

SETSCREENCOLOR PROC NEAR
    MOV AH, 06H
    MOV AL, 00H
    MOV BH, 0BCH
    MOV CX, 0000H
    MOV DX, 184FH
    
    INT 10H
    
    RET
SETSCREENCOLOR ENDP

DISPLAYCHAR PROC NEAR
    MOV AH, 0AH
    MOV CX, 1
    
    INT 10H
    
    RET
DISPLAYCHAR ENDP 

SETCURSORPOS PROC NEAR
    MOV AH, 02
    MOV BH, 00
    
    INT 10H
    
    RET
SETCURSORPOS ENDP

DISPLAYSTRING PROC NEAR
    MOV DH, 0CH
    MOV DL, STARTINGCURSOR
    CALL SETCURSORPOS
    
    LEA SI, PREGREET
    DISPLAYGREETING:
        MOV AL, [SI]
        CALL DISPLAYCHAR
        INC SI
        INC DL
        INC CTR
        CALL SETCURSORPOS
        MOV AL, GREETLEN
        CMP CTR, AL
        JNE DISPLAYGREETING
        
    DEC DL
    CALL SETCURSORPOS
    MOV CTR, 0
    LEA SI, KB_DATA
    DISPLAYNAME:
        MOV AL, [SI]
        CALL DISPLAYCHAR
        INC SI
        INC DL
        INC CTR 
        CALL SETCURSORPOS
        MOV AL, ACT_LEN
        CMP CTR, AL
        JNE DISPLAYNAME
    
    DISPLAYEND:
        MOV AL, 21H
        CALL DISPLAYCHAR
    
    
    RET
DISPLAYSTRING ENDP

