.MODEL SMALL
.STACK 64
.DATA
MAX_LEN DB 3
KB_DATA DB 3 DUP(0)
MATCH DB 0 
CTR DB 0

SMSG DB 'SUCCESS!'
FMSG DB 'FAILED.'
CENTERCURSOR DB 80

.CODE
MAIN PROC NEAR
    MOV AX, @DATA
    MOV ES, AX
    MOV DS, AX
    
    MOV CH, 00
    CALL TAKEINPUT
    CALL TAKESECONDINPUT 
    CMP MATCH, 1
    JE YES
    JMP NO
    
    YES:
        CALL SUCCESS
        JMP EXITPROGRAM   
    
    NO:
        CALL FAILED
        
    EXITPROGRAM:
        
    MOV AX, 4C00H
    INT 21H
MAIN ENDP

INPUTSCAN PROC NEAR
    MOV AH, 00H
    INT 16H
                         
    RET              
INPUTSCAN ENDP

TAKEINPUT PROC NEAR
    LEA SI, KB_DATA 
    MOV CL, MAX_LEN
    WRITE:
        CALL INPUTSCAN
        MOV [SI], AH
        INC SI
    
    LOOP WRITE
    
    RET   
TAKEINPUT ENDP

TAKESECONDINPUT PROC NEAR
    LEA SI, KB_DATA
    
    MOV CL, MAX_LEN
    CHECK:
        CALL INPUTSCAN
        CMP AH, [SI]
        JNE EXIT
        INC SI  
    LOOP CHECK
    
    MOV MATCH, 1
    
    EXIT:
    RET   
TAKESECONDINPUT ENDP
SETVIDEOMODE PROC NEAR
    MOV AH, 00H
    MOV AL, 03H
    
    INT 10H
    RET
SETVIDEOMODE ENDP

SETSCREEN PROC NEAR
    MOV AH, 06H
    MOV AL, 00H
    MOV CX, 0000H
    MOV DX, 184FH
    
    INT 10H
    RET    
SETSCREEN ENDP

SUCCESSCURSORPOS PROC NEAR
    SUB CENTERCURSOR,8 
    MOV AH,00
    MOV AL, CENTERCURSOR
    MOV BL, 2
    DIV BL
    MOV CENTERCURSOR, AL
    
    RET    
SUCCESSCURSORPOS ENDP

FAILEDCURSORPOS PROC NEAR 
    SUB CENTERCURSOR, 7
    MOV AH,00
    MOV AL, CENTERCURSOR
    MOV BL, 2
    DIV BL
    MOV CENTERCURSOR, AL
    
    RET  
FAILEDCURSORPOS ENDP

SETCURSOR PROC NEAR 
    
    MOV AH, 02H
    MOV BH, 00H
    
    MOV DH, 0CH
    MOV DL, CENTERCURSOR 
    INT 10H
    RET   
SETCURSOR ENDP

DISPLAYMSG PROC NEAR
    MOV AH, 0AH
    MOV CX, 1
    INT 10H
    
    RET
DISPLAYMSG ENDP    

SUCCESS PROC NEAR
    CALL SETVIDEOMODE 
    MOV BH, 0FAH
    CALL SETSCREEN 
    CALL SUCCESSCURSORPOS
    CALL SETCURSOR 
    
    LEA SI, SMSG
    
    SDISPLAY:
        MOV AL, [SI]
        CALL DISPLAYMSG
        INC CTR
        CMP CTR, 8
        JE S_END
        INC SI
        INC CENTERCURSOR
        CALL SETCURSOR
        JMP SDISPLAY
         
    S_END:
        RET    
SUCCESS ENDP

FAILED PROC NEAR
    CALL SETVIDEOMODE 
    MOV BH, 00CH
    CALL SETSCREEN 
    CALL FAILEDCURSORPOS
    CALL SETCURSOR
    
    LEA SI, FMSG
    
    FDISPLAY:
        MOV AL, [SI]
        CALL DISPLAYMSG
        INC CTR
        CMP CTR, 7
        JE F_END
        INC SI
        INC CENTERCURSOR
        CALL SETCURSOR
        JMP FDISPLAY
         
    F_END:
        RET 
    
    
FAILED ENDP    
    

