.MODEL SMALL
.STACK 64
.DATA
 B DB 2FH
 F DB 5CH 
 S DB 20H 
 U DB 5FH
 SPACECTR DB 0
 INNERCTR DB 0
 SPACETRACKER DB 0 
 
 ENTRY DB 24 DUP(?)
 ENTRYCTR DB 2
 
 CENTERPOS DB 39
 ROWPOS DB 06
 
 TEMPCOL DB ?
 TEMPROW DB ? 
 
 UPPERCYCLE DB 11
 
.CODE
MAIN PROC NEAR  
    MOV AX, @DATA
    MOV ES, AX
    MOV DS, AX
    
    CALL SETVIDEOMODE 
    CALL SETGROUND
    MOV DH, 00
   
    UPPER: 
        DEC UPPERCYCLE
        MOV ENTRYCTR, 2
        CALL WRITETOENTRY
        
        MOV DH, ROWPOS
        MOV DL, CENTERPOS
        CALL SETCURSORPOSITION
        CALL DISPLAYENTRY
        
        
         
        ;RESET/UPDATES GOES HERE
        INC ROWPOS
        DEC CENTERPOS
        INC SPACETRACKER
        CALL UPDATESPACECTR
        
        
        CMP UPPERCYCLE, 0
        JNE UPPER
        
    
             
    MOV AX, 4C00H
    INT 21H
MAIN ENDP
UPDATESPACECTR PROC NEAR
    MOV AH, 00
    MOV AL, SPACETRACKER
    PUSH AX
    MOV BL, 2
    MUL BL
    MOV SPACECTR, AL
    POP AX
    MOV SPACETRACKER, AL
    RET
UPDATESPACECTR ENDP    
DISPLAYENTRY PROC NEAR
    LEA SI, ENTRY
    MOV TEMPCOL, DL
    
    DISPLAY:
        MOV AL, [SI]
        CALL DISPLAYCHAR 
        INC SI
        INC TEMPCOL
        MOV DL, TEMPCOL
        CALL SETCURSORPOSITION
        DEC ENTRYCTR
        CMP ENTRYCTR, 0
        JNE DISPLAY
 
    RET
DISPLAYENTRY ENDP

DISPLAYCHAR PROC NEAR
    MOV AH, 0AH
    MOV CX, 1
    INT 10H
    
    RET
DISPLAYCHAR ENDP

SETCURSORPOSITION PROC NEAR
    MOV AH, 02H
    MOV BH, 00H
    
    INT 10H   
    RET  
SETCURSORPOSITION ENDP

WRITETOENTRY PROC NEAR 
    MOV BH, ENTRYCTR
    MOV AL, SPACECTR
    MOV INNERCTR, AL
    LEA SI, ENTRY
    
    MOV AL, B
    MOV [SI], AL
    
    CMP INNERCTR, 0
    JE FF
    
    CMP UPPERCYCLE, 0
    JE INSERTUNDERLINE
    
    INSERTSPACE:
        MOV AL, S
        INC SI
        MOV [SI], AL
        INC ENTRYCTR
        DEC INNERCTR
        CMP INNERCTR, 0
        JNE INSERTSPACE
        JMP FF
        
    INSERTUNDERLINE: 
        MOV AL, U
        INC SI
        MOV [SI], AL
        INC ENTRYCTR
        DEC INNERCTR
        CMP INNERCTR, 0
        JNE INSERTUNDERLINE
    
       
    
    FF: 
        INC SI
        MOV AL, F
        MOV [SI], AL
    
    
    RET
WRITETOENTRY ENDP 

SETVIDEOMODE PROC NEAR
    MOV AH, 00H
    MOV AL, 03H
    INT 10H
    
    RET
SETVIDEOMODE ENDP

SETGROUND PROC NEAR
    MOV AH, 06H
    MOV AL, 00H
    MOV BH, 0FCH 
    MOV CX, 0000H
    MOV DX, 184FH
    INT 10H
    
    RET
SETGROUND ENDP


